<template>
  <div>
  <Header />
  <div class="container"><div class="row"><div class="col-md-12"><h3>1. HƯỚNG DẪN THỦ TỤC</h3><dl class="accordion"><dt class="active"><a href="">CẤP HỘ CHIẾU PHỔ THÔNG</a></dt><dd class="active" style="display: block;"><p><strong>1. Hồ sơ bao gồm:</strong></p><p>- Khai 01 tờ khai đề nghị cấp hộ chiếu theo mẫu quy định (X01).<br>
  - 02 ảnh cỡ 4x6, nền trắng, mặt nhìn thẳng, đầu để trần, không đeo kính màu (chụp ảnh tại cơ sở chụp ảnh được cơ quan Quản lý xuất nhập cảnh cho phép)<br>
  - Giấy chứng minh nhân dân hoặc Thẻ căn cước công dân còn giá trị (xuất trình khi nộp hồ sơ để cơ quan Quản lý xuất nhập cảnh kiểm tra, đối chiếu).<br>
  - Sổ tạm trú (nếu nộp hồ sơ tại nơi tạm trú).</p><p><strong>2. Lệ phí: 200.000 đ <i>(Hai trăm nghìn đồng)</i>.</strong></p></dd><dt><a href="">CẤP LẠI HỘ CHIẾU DO BỊ HƯ HỎNG, BỊ MẤT</a></dt><dd style="display: none;"><p><strong>1. Hồ sơ bao gồm:</strong></p><p>- Khai 01 tờ khai đề nghị cấp hộ chiếu theo mẫu quy định (X01).<br>
  - 02 ảnh cỡ 4x6, nền trắng, mặt nhìn thẳng, đầu để trần, không đeo kính màu (chụp ảnh tại cơ sở chụp ảnh được cơ quan Quản lý xuất nhập cảnh cho phép).<br>
  - Giấy chứng minh nhân dân hoặc Thẻ căn cước công dân còn giá trị (xuất trình khi nộp hồ sơ để cơ quan Quản lý xuất nhập cảnh kiểm tra, đối chiếu).<br>
  - Trường hợp hộ chiếu bị hư hỏng: nộp lại cho cơ quan Quản lý xuất nhập cảnh.<br>
  - Trường hợp hộ chiếu bị mất: nộp kèm đơn báo mất (mẫu <a target="_blank" href="https://hochieu.xuatnhapcanh.gov.vn/docs/Mau_don_bao_mat_ho_chieu_X08.doc">X08</a>) hoặc đơn trình bày về việc bị mất hộ chiếu.<br></p><p><strong>2. Lệ phí: 400.000 đ <i>(Bốn trăm nghìn đồng)</i>.</strong></p></dd><dt><a href="">CẤP LẠI HỘ CHIẾU DO HỘ CHIẾU CŨ SẮP HẾT HẠN HOẶC HẾT TRANG </a></dt><dd style="display: none;"><p><strong>1. Hồ sơ bao gồm:</strong></p><p>- Khai 01 tờ khai đề nghị cấp hộ chiếu theo mẫu quy định (X01).<br>
  - 02 ảnh cỡ 4x6, nền trắng, mặt nhìn thẳng, đầu để trần, không đeo kính màu (chụp ảnh tại cơ sở chụp ảnh được cơ quan Quản lý xuất nhập cảnh cho phép).<br>
  - Giấy chứng minh nhân dân hoặc Thẻ căn cước công dân còn giá trị (xuất trình khi nộp hồ sơ để cơ quan Quản lý xuất nhập cảnh kiểm tra, đối chiếu).<br>
  - Hộ chiếu phổ thông còn giá trị.</p><p><strong>2. Lệ phí: 200.000 đ <i>(Hai trăm nghìn đồng)</i>.</strong></p><p><strong>3. Lưu ý:</strong><br>
  Trường hợp người đề nghị có nguyện vọng được giữ lại hộ chiếu thì đề nghị ghi rõ lý do vào mục 14.  
  </p></dd><dt><a href="">CẤP CHUNG HỘ CHIẾU PHỔ THÔNG CHO CÔNG DÂN VÀ TRẺ EM DƯỚI 9 TUỔI</a></dt><dd style="display: none;"><p><strong>1. Hồ sơ bao gồm:</strong></p><p>- Khai 01 tờ khai đề nghị cấp hộ chiếu theo mẫu quy định (X01).<br>
  - 02 ảnh của trẻ em, cỡ 3x4, 02 ảnh của cha hoặc mẹ, cỡ 4x6, nền trắng, mặt nhìn thẳng, đầu để trần, không đeo kính màu.<br>
  - Giấy chứng minh nhân dân hoặc Thẻ căn cước công dân còn giá trị (xuất trình khi nộp hồ sơ để cơ quan Quản lý xuất nhập cảnh kiểm tra, đối chiếu).<br>
  - Bản sao Giấy khai sinh của trẻ em (khi đến nộp xuất trình bản chính để đối chiếu).<br>
  - Sổ tạm trú (nếu nộp hồ sơ tại nơi tạm trú).</p><p><strong>2. Lệ phí: </strong></p><p>- Hộ chiếu kèm 01 trẻ em: <strong>250.000 đ (Hai trăm năm mươi nghìn đồng)</strong>.<br>
  - Hộ chiếu kèm 02 trẻ em: <strong>300.000 đ (Ba trăm nghìn đồng)</strong>.</p><p><strong>3. Lưu ý:</strong></p><p> - Trường hợp cấp chung 02 trẻ em vào hộ chiếu của cha hoặc mẹ, sau khi nhập thông tin phải in 02 tờ khai (mỗi tờ tương ứng với thông tin của 01 trẻ em).<br>
  - Tờ khai và ảnh của trẻ em phải có xác nhận và giáp lai ảnh của Công an phường, xã, thị trấn nơi trẻ em thường trú hoặc tạm trú.<br>
  - Hộ chiếu của cha, mẹ cấp chung với con dưới 9 tuổi có thời hạn 05 năm.</p></dd><dt><a href="">CẤP RIÊNG HỘ CHIẾU PHỔ THÔNG CHO TRẺ EM DƯỚI 14 TUỔI</a></dt><dd style="display: none;"><p><strong>1. Hồ sơ bao gồm:</strong></p><p>- Khai 01 tờ khai đề nghị cấp hộ chiếu theo mẫu quy định (X01).<br>
  - 02 ảnh cỡ 4x6, nền trắng, mặt nhìn thẳng, đầu để trần, không đeo kính màu.<br>
  - Bản sao Giấy khai sinh (khi đến nộp xuất trình bản chính để đối chiếu).<br>
  - Sổ tạm trú (nếu nộp hồ sơ tại nơi tạm trú).</p><p><strong>2. Lệ phí: 200.000 đ (Hai trăm nghìn đồng).</strong></p><p><strong>3. Lưu ý:</strong></p><p>- Sau khi nhập thông tin tờ khai cha hoặc mẹ hoặc nguời giám hộ ký thay và dán ảnh vào tờ khai để lấy xác nhận, giáp lai ảnh của Công an phường, xã, thị trấn nơi trẻ em thường trú hoặc tạm trú.</p><p>- Nếu người giám hộ khai và ký thay thì nộp kèm giấy tờ chứng minh quyền giám hộ trẻ em đó.</p></dd><dt class=""><a href="">SỬA ĐỔI, BỔ SUNG THÔNG TIN TRONG HỘ CHIẾU</a></dt><dd style="display: none;" class=""><p><strong>1. Hồ sơ bao gồm:</strong></p><p>- Khai 01 tờ khai đề nghị cấp, sửa đổi hộ chiếu phổ thông theo mẫu quy định (X01).<br>
  - Hộ chiếu phổ thông còn giá trị ít nhất 01 năm.<br>
  - Giấy chứng minh nhân dân hoặc Thẻ căn cước công dân còn giá trị (xuất trình khi nộp hồ sơ để cơ quan Quản lý xuất nhập cảnh kiểm tra, đối chiếu).</p><p><strong><i>- Ngoài ra, đối với từng trường hợp cụ thể cần bổ sung các giấy tờ sau:</i></strong><br>
  + Trường hợp đề nghị sửa chi tiết trang nhân thân trong hộ chiếu (điều chỉnh họ, tên; ngày, tháng, năm sinh; nơi sinh; giới tính; số Giấy chứng minh nhân dân hoặc Thẻ căn cước công dân) thì nộp kèm giấy tờ pháp lý chứng minh sự điều chỉnh đó.<br>
  + Trường hợp đề nghị sửa đổi, bổ sung hộ chiếu cho trẻ em dưới 14 tuổi thì tờ khai do cha hoặc mẹ hoặc người giám hộ khai và ký thay, được Trưởng Công an phường, xã, thị trấn nơi trẻ em đó thường trú hoặc tạm trú xác nhận, đóng dấu giáp lai ảnh, kèm theo.<br>
  + Trường hợp đề nghị bổ sung trẻ em dưới 9 tuổi vào hộ chiếu của cha hoặc mẹ thì kèm theo hộ chiếu của cha hoặc mẹ.</p><p><strong>2. Lệ phí: 50.000 đ (Năm mươi nghìn đồng).</strong><br>
  Trường hợp bổ sung 02 trẻ em dưới 9 tuổi vào hộ chiếu của cha hoặc mẹ thì lệ phí là <strong>100.000 đ (Một trăm nghìn đồng)</strong>.</p><p><strong>3. Lưu ý: </strong></p><p>Nếu người giám hộ khai và ký thay thì nộp bản sao hoặc bản chụp có chứng thực giấy tờ chứng minh quyền giám hộ.</p></dd></dl></div></div><div class="row"><div class="col-md-12"><h3>2. Nơi nộp hồ sơ</h3></div><div class="col-md-12"><p>- Người đề nghị cấp hộ chiếu lần đầu, đề nghị cấp lại hộ chiếu do hết hạn trực tiếp nộp hồ sơ tại Phòng Quản lý xuất nhập cảnh Công an tỉnh, thành phố trực thuộc Trung ương nơi thường trú hoặc tạm trú.</p><p>- Người đề nghị cấp hộ chiếu do sắp hết hạn, do hư hỏng hoặc bị mất, đề nghị sửa đổi, bổ sung hộ chiếu nộp hồ sơ tại Phòng Quản lý xuất nhập cảnh Công an tỉnh, thành phố trực thuộc Trung ương nơi thường trú, tạm trú hoặc Cục Quản lý xuất nhập cảnh, Bộ Công an.</p></div></div><div class="row"><div class="col-md-12" style="font-size:12px;"><p><strong>Lưu ý:</strong></p><p><i>- Người khai thông tin phải chịu trách nhiệm về tính xác thực của nội dung đã khai. Đối với trường hợp gửi hồ sơ đề nghị cấp lại hộ chiếu qua đường Bưu điện, trường hợp trẻ em dưới 14 tuổi đề nghị cấp hộ chiếu hoặc trường hợp ủy thác cho cơ quan, tổ chức, doanh nghiệp có tư cách pháp nhân nộp hồ sơ đề nghị cấp hộ chiếu, sau khi khai tờ khai điện tử người đề nghị phải in tờ khai và dán ảnh vào tờ khai để lấy xác nhận và giáp lai ảnh của Công an phường, xã, thị trấn nơi thường trú hoặc tạm trú hoặc Thủ trưởng cơ quan, tổ chức, doanh nghiệp được ủy thác. Đối với trường hợp trực tiếp nộp hồ sơ, người đề nghị cấp hộ chiếu có thể chụp ảnh bằng cách liên hệ với cơ sở chụp ảnh được cơ quan Quản lý xuất nhập cảnh cho phép.</i></p><p><i>- Trường hợp đề nghị cấp chung 02 trẻ em vào hộ chiếu của cha hoặc mẹ, sau khi nhập thông tin phải in 02 tờ khai (mỗi tờ tương ứng với thông tin của 01 trẻ em) để lấy xác nhận của Công an phường, xã, thị trấn nơi trẻ em thường trú hoặc tạm trú; trong trường hợp này, hộ chiếu của cha, mẹ cấp chung với con dưới 9 tuổi có thời hạn 05 năm.</i></p></div></div><div class="row"><div class="col-md-12"><h3>Trình tự thực hiện khai tờ khai điện tử đề nghị cấp hộ chiếu</h3></div><div class="col-md-12"><p><strong>Bước 1: </strong> Nhập đầy đủ thông tin tờ khai đề nghị cấp hộ chiếu.</p></div><div class="col-md-12"><p><strong>Bước 2: </strong> In tờ khai đề nghị cấp hộ chiếu (tại nhà hoặc tại nơi nộp hồ sơ).</p></div><div class="col-md-12"><p><strong>Bước 3: </strong> Kiểm tra, chỉnh sửa thông tin đã khai (nếu có nhu cầu) <a href="adf.task-flow?_id=task-flow-edit&amp;_document=/WEB-INF/task-flow-edit.xml">tại đây</a></p></div><div class="col-md-12"><p><strong>Bước 4: </strong> Đặt lịch hẹn nộp hồ sơ (nếu có nhu cầu).</p></div><div class="col-md-12"><p><strong>Bước 5: </strong> Đến nộp hồ sơ tại cơ quan Quản lý xuất nhập cảnh.</p></div></div>
  </div>
  </div>
</template>

<script>
  export default {
    components: {
      Header: () => import('@/components/Header'),
    }
  }
</script>